# Generated by Django 2.1.5 on 2019-01-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20190112_2351'),
        ('teams', '0003_auto_20190112_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='candidates',
        ),
        migrations.AddField(
            model_name='team',
            name='candidates',
            field=models.ManyToManyField(blank=True, null=True, to='people.Participant'),
        ),
    ]
