# Generated by Django 2.1.5 on 2019-01-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20190112_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='candidates',
            field=models.ManyToManyField(blank=True, to='people.Participant'),
        ),
    ]
