# Generated by Django 2.1.5 on 2019-01-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190113_0118'),
        ('teams', '0005_auto_20190113_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='needed_skill',
            field=models.ManyToManyField(blank=True, to='people.Skill'),
        ),
    ]
