# Generated by Django 2.1.5 on 2019-01-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_needed_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
