# Generated by Django 2.1.5 on 2019-01-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_hackathon_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='max_size',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
