# Generated by Django 2.1.5 on 2019-01-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_auto_20190113_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='descprition',
            new_name='description',
        ),
    ]
