# Generated by Django 2.1.5 on 2019-01-13 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_auto_20190113_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='facebook_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
