# Generated by Django 2.1.5 on 2019-01-12 13:14

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190112_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='email@domain.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='skills',
            field=models.ManyToManyField(to='people.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='advanced_level',
            field=models.SmallIntegerField(validators=[people.models.advance_level_validator]),
        ),
    ]
