# Generated by Django 2.1.5 on 2019-01-12 13:28

from django.db import migrations, models
import django.db.models.deletion
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190112_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced_level', models.SmallIntegerField(validators=[people.models.advance_level_validator])),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='advanced_level',
        ),
        migrations.AlterField(
            model_name='participant',
            name='skills',
            field=models.ManyToManyField(to='people.ParticipantSkill'),
        ),
        migrations.AddField(
            model_name='participantskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Skill'),
        ),
    ]
