# Generated by Django 2.1.5 on 2019-01-12 22:12

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='skills',
            field=models.ManyToManyField(blank=True, to='people.ParticipantSkill'),
        ),
        migrations.AlterField(
            model_name='participantskill',
            name='advanced_level',
            field=models.SmallIntegerField(default=1, validators=[people.models.advance_level_validator]),
        ),
    ]
