# Generated by Django 2.1.5 on 2019-01-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20190112_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='skills',
        ),
        migrations.AddField(
            model_name='participantskill',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.Participant'),
            preserve_default=False,
        ),
    ]
