# Generated by Django 2.1.5 on 2019-01-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20190112_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
    ]
