# Generated by Django 2.1.5 on 2019-01-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20190113_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='short_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
